language: python
jobs:
  include:
    - name: "Python 3.4.0 on Linux"
      python: 3.4
    - name: "Python 3.5.0 on Linux"
      python: 3.5
    - name: "Python 3.6.0 on Linux"
      python: 3.6
    - name: "Python 3.7.0 on Linux"
      python: 3.7
    - name: "Python 3.8.0 on Linux"
      python: 3.8
    - name: "Python 3.4.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.4.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python34:/c/Python34/Scripts:$PATH
    - name: "Python 3.5.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install -q coveralls
  - pip3 install -r requirements.txt
script:
  - ./run_tests.sh
after_success:
  - coveralls
